### ISSUE TITLE
using ./src/luajit-x -bl tests/test-1.lua gives => invalid header

### ISSUE THREAD

**Issue by Wiladams** [franko/luajit-lang-toolkit#21]
./lang/bcread.lua:717: invalid header

This is running on Ubuntu Linux with a luajit 2.1 installed.

Pretty much the same error when running with just luajit instead of luanit-x

**Comment by franko** [comment]
Hi,

the language toolkit supports only LuaJIT 2.0 bytecode. The bytecode's header contains the information about the LuaJIT bytecode's version and bcread immediately give up when it does encounter the 2.1 version tag.

Normally implementing support for 2.1 bytecode require some works.

**Comment by Wiladams** [comment]
OK.  So, what you're saying is if I just use 2.0, it should work right?


I hope you do upgrade to 2.1, as there have been quite a lot of bug fixes and performance improvements.


-- William



===============================
- Shaping clay is easier than digging it out of the ground.


________________________________

**Comment by franko** [comment]
Yes, with 2.0 everything should work fine. The language toolkit has a quite large test suite that cover almost every aspect.

As for 2.1 I note that you are interested. I think also that it is interesting to have but for the moment I don't have a lot of spare time to work on that but in the future I'm probably going to do it.

**Comment by Wiladams** [comment]
Ok.  For what I am doing, 2.0 is ok.


Sent from my Windows Phone

-----Original Message-----

**Comment by Wiladams** [comment]
Using luajit 2.0 works fine, thanks.

Are there any grammars for 'C' or other languages besides Lua as yet?


-- William



===============================
- Shaping clay is easier than digging it out of the ground.


________________________________

**Comment by franko** [comment]
Short answer: no. :-)

I would love to have another grammar to show an example of the usage of the parser but nothing other than Lua is available right now.
