### ISSUE TITLE
Parenthesis dropped in generated Lua

### ISSUE THREAD

**Issue by gnois** [franko/luajit-lang-toolkit#27]
```
print(("hi"):rep(3))
```
gives
```
print("hi":rep(3))

Output:
lua: run.lua:70: [string "print("\..."]:3: ')' expected near ':'
```
Due to the parenthesis were dropped.

**Comment by franko** [comment]
Fixed in git HEAD with commit franko@8ddc901ac48c. I've also added a few test cases.

Thank you for reporting that.
