### ISSUE TITLE
`TK_dots` undefined

### ISSUE THREAD

**Issue by praisethemoon** [franko/luajit-lang-toolkit#37]
Is it just me or `TK_dots` is not defined in `lexer.lua`?

Cheers :heart:

**Comment by franko** [comment]
Hi,

you don't need a definition because TK_dots and company are just strings. The lexer just returns TK_dots (a string) when appropriate, see the fragment below:

```lua
        elseif current == '.' then
            save_and_next(ls)
            if ls.current == '.' then
                nextchar(ls)
                if ls.current == '.' then
                    nextchar(ls)
                    return 'TK_dots' -- ...
                end
                return 'TK_concat' -- ..
            elseif not char_isdigit(ls.current) then
                return '.'
            else
                return 'TK_number', lex_number(ls)
            end
```

**Comment by praisethemoon** [comment]
Oh okay, thanks for the tip! By the way I am designing a Java-like language using this toolkit, is there any piece of advice you can give me? 

Cheers 🍺

**Comment by franko** [comment]
Wow, a Java like language! Bon courage :-)

I don't think a can give you a really useful advice, I'm not an expert about programming language.

Yet if you want to share something I may give a look to what you're doing as soon as you have something. It can be just the ideas or the code itself.

**Comment by praisethemoon** [comment]
Oh, thank you! I have already finished the lexer, moving to the parser. We will see how it goes.
I'll keep you updated! 

Cheers :100:
